Add error handling

diff --git a/Jenkinsfile.CI b/Jenkinsfile.CI
--- a/Jenkinsfile.CI
+++ b/Jenkinsfile.CI
@@ -78,8 +78,17 @@ pipeline {
             steps {
                 withCredentials([sshUserPrivateKey(credentialsId: "agent.jenkins", keyFileVariable: 'keyfile')]) {
                     sh '''#!/usr/bin/bash
-                        set -e
+                        set +e
                         ./scenario.deploy
+                        if [ $? -ne 1 ]; then
+                            echo "Error: deploy script: error code 1 expected but $?"
+                            exit 1
+                        fi
+                        ./scenario.deploy -h
+                        if [ $? -ne 0 ]; then
+                            echo "Error: deploy script: error code 0 expected but $?"
+                            exit 1
+                        fi
                     '''
                 }
             }
