Fix RV

diff --git a/Jenkinsfile.CI b/Jenkinsfile.CI
--- a/Jenkinsfile.CI
+++ b/Jenkinsfile.CI
@@ -80,13 +80,15 @@ pipeline {
                     sh '''#!/usr/bin/bash
                         set +e
                         ./scenario.deploy
-                        if [ $? -ne 1 ]; then
-                            echo "Error: deploy script: error code 1 expected but $?"
+                        RV=$?
+                        if [ $RV -ne 1 ]; then
+                            echo "Error: deploy script: error code 1 expected but $RV"
                             exit 1
                         fi
-                        ./scenario.deploy -h
-                        if [ $? -ne 0 ]; then
-                            echo "Error: deploy script: error code 0 expected but $?"
+                        ./scenario.deploy scenarion.name -h
+                        RV=$?
+                        if [ $RV -ne 0 ]; then
+                            echo "Error: deploy script: error code 0 expected but $RV"
                             exit 1
                         fi
                     '''
