Fix error handling

diff --git a/Jenkinsfile.CI b/Jenkinsfile.CI
--- a/Jenkinsfile.CI
+++ b/Jenkinsfile.CI
@@ -78,19 +78,21 @@ pipeline {
             steps {
                 withCredentials([sshUserPrivateKey(credentialsId: "agent.jenkins", keyFileVariable: 'keyfile')]) {
                     sh '''#!/usr/bin/bash
+                        function checkError() {
+                          RV=$1
+                          EXP=$2
+                          MSG=$3
+                          if [ $RV -ne $EXP ]; then
+                            echo "Error: return value $EXP expected but $RV : $MSG"
+                            exit 1
+                          fi
+                        }
+
                         set +e
                         ./scenario.deploy
-                        RV=$?
-                        if [ $RV -ne 1 ]; then
-                            echo "Error: deploy script: error code 1 expected but $RV"
-                            exit 1
-                        fi
-                        ./scenario.deploy scenarion.name -h
-                        RV=$?
-                        if [ $RV -ne 0 ]; then
-                            echo "Error: deploy script: error code 0 expected but $RV"
-                            exit 1
-                        fi
+                        checkError $? 1 "no arguments should return an error value (1)"
+                        ./scenario.deploy de/wo-da/test/dev-ci -h
+                        checkError $? 0 "help should return 0"
                     '''
                 }
             }
